### ISSUE TITLE
1.16.2+ version?

### ISSUE THREAD

**Issue by t0mtee** [DimiDimit/Custom-LAN#1]

**Comment by DimiDimit** [comment]
1.17 brought us:
* Java 16
* `CyclingButtonWidget` (`net.minecraft.client.gui.widget`)
* `Screen#addDrawableChild`

After replacing the usages of those (and being thankful for their existence in the new version), the port was fairly straightforward.
The JAR only works on Minecraft 1.16.2+, however, due to `fabric-resource-loader-v0`. If you need one for 1.16 or 1.16.1, tell me.
